apiVersion: extensions/v1beta1
commonLabels:
  app: favorite-beer
kind: Ingress
metadata:
  name: favorite-beer
spec:
  rules:
    - host: favorite-beer
      http:
        paths:
          - path: /
            backend:
              serviceName: favorite-beer
              servicePort: http
