apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  template:
    metadata:
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 80
        volumeMounts:
        - name: redis-data
          mountPath: /data
        imagePullPolicy: IfNotPresent
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      resources:
        requests:
          storage: 1Gi
      accessModes: ["ReadWriteOnce"]
      storageClassName: manual
  serviceName: redis
