apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "favorite-beer.fullname" . }}-redis
spec:
  podSelector:
    matchLabels:
      app: {{ template "favorite-beer.name" . }}-redis
      release: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ template "favorite-beer.name" . }}-redis
              release: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 6379