steps:
- checkout: self
  persistCredentials: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git checkout -b master
      git config --global user.email "system-azure-devops@redapt.com"
      git config --global user.name "System"
      $version = [IO.File]::ReadAllText("VERSION")
      $versionParts = $version.TrimEnd("*-").Split(".")
      $currentMajor = [Convert]::ToInt32($versionParts[0])
      $currentMinor = [Convert]::ToInt32($versionParts[1])
      $currentPatch = [Convert]::ToInt32($versionParts[2])
      $currentPatch++
      Write-Output "##vso[task.setvariable variable=buildVersionMajor]$currentMajor"
      Write-Output "##vso[task.setvariable variable=buildVersionMinor]$currentMinor"
      Write-Output "##vso[task.setvariable variable=buildVersionPatch]$currentPatch"
      $version = $currentMajor + '.' + $currentMinor + '.' + $currentPatch
      Set-Content -Path VERSION -Value $version
      git status
      git add VERSION
      git commit -m "[skip ci] Update version numbers for Build %version%"
      git push origin master
