steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: $(dockerRegistryServiceConnection)
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $version = $env:buildVersionMajor + '.' + $env:buildVersionMinor + '.' + $env:buildVersionPatch + '-rc'
      docker pull $env:containerRegistry/$env:imageRepository:$version
      docker tag $env:containerRegistry/$env:imageRepository:$version-rc $env:containerRegistry/$env:imageRepository:$version
      docker push $env:containerRegistry/$env:imageRepository:$version
